create FUNCTION TS_DAY(ts TIMESTAMP) RETURNS VARCHAR(10)
  DETERMINISTIC
  PARAMETER STYLE JAVA NO SQL LANGUAGE JAVA
  EXTERNAL NAME 'be.echostyle.moola.peristence.derby.TimeFunctions.day';

create FUNCTION TS_WEEK(ts TIMESTAMP) RETURNS VARCHAR(10)
  DETERMINISTIC
  PARAMETER STYLE JAVA NO SQL LANGUAGE JAVA
  EXTERNAL NAME 'be.echostyle.moola.peristence.derby.TimeFunctions.week';

create FUNCTION TS_MONTH(ts TIMESTAMP) RETURNS VARCHAR(10)
  DETERMINISTIC
  PARAMETER STYLE JAVA NO SQL LANGUAGE JAVA
  EXTERNAL NAME 'be.echostyle.moola.peristence.derby.TimeFunctions.month';

create FUNCTION TS_YEAR(ts TIMESTAMP) RETURNS VARCHAR(10)
  DETERMINISTIC
  PARAMETER STYLE JAVA NO SQL LANGUAGE JAVA
  EXTERNAL NAME 'be.echostyle.moola.peristence.derby.TimeFunctions.year';