CREATE OR REPLACE FUNCTION TS_DAY(timestamp) RETURNS date AS $$
   SELECT $1::date $$ LANGUAGE SQL;

CREATE OR REPLACE FUNCTION TS_WEEK(timestamp) RETURNS text AS $$
   SELECT EXTRACT(YEAR FROM $1) || '/' || LPAD(EXTRACT(WEEK FROM $1)::text, 2, '0') $$ LANGUAGE SQL;

CREATE OR REPLACE FUNCTION TS_MONTH(timestamp) RETURNS text AS $$
   SELECT EXTRACT(YEAR FROM $1) || '-' || LPAD(EXTRACT(MONTH FROM $1)::text, 2, '0') $$ LANGUAGE SQL;

CREATE OR REPLACE FUNCTION TS_YEAR(timestamp) RETURNS text AS $$
   SELECT EXTRACT(YEAR FROM $1) || '' $$ LANGUAGE SQL;
